name: Integration Tests

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 35
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v14
      - uses: actions/checkout@v6
      - name: Run integration tests
        run: nix develop -c make test-in-ci
